"""add latitude and longitude to schedules

Revision ID: c46d61e376ad
Revises: 7d339ca41741
Create Date: 2025-09-01 20:03:57.874878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46d61e376ad'
down_revision: Union[str, Sequence[str], None] = '7d339ca41741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('latitude', sa.String(length=30), nullable=True))
    op.add_column('schedules', sa.Column('longitude', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'longitude')
    op.drop_column('schedules', 'latitude')
    # ### end Alembic commands ###
